### ISSUE TITLE
Remove Yandex Counter from ecampus.kpi.ua

### ISSUE THREAD

**Issue by ernado-x** [kpi-ua/intellect.kpi.ua#7]

**Comment by KovalenkoStas** [comment]
There is no Yandex Counter on ecampus.kpi.ua repo. It seems that Yandex metrika counter appear only on production and left on prod from previous versions.
![image](https://user-images.githubusercontent.com/15806486/37801808-a6858d08-2e30-11e8-88e8-cc562ae3f58e.png)

**Comment by KovalenkoStas** [comment]
Also that issue might be moved to ecampus.kpi.ua repo.

**Comment by ernado-x** [comment]
Sorry. You are right!
