### ISSUE TITLE
Review the implementation of search filters

### ISSUE THREAD

**Issue by lizozavr** [kpi-ua/intellect.kpi.ua#80]
Update the interface to include a list of available filters and a search bar, allowing users to find teachers by their full name:

![Снимок экрана 2023-11-28 в 19 57 32](https://github.com/kpi-ua/api.campus.kpi.ua/assets/58970455/7ac11064-ccb8-4760-9eb9-1fee4bb6cf4a)

By clicking on 'Filters,' display a list of filters. After selecting one of them, allow the user to enter a search parameter into the search bar:

![Снимок экрана 2023-11-28 в 20 01 28](https://github.com/kpi-ua/api.campus.kpi.ua/assets/58970455/bee21f24-1d28-4733-b346-b5971367c639)

![Снимок экрана 2023-11-28 в 20 09 53](https://github.com/kpi-ua/api.campus.kpi.ua/assets/58970455/c9512a3a-b613-409a-8a39-4d6cc704bd0f)

After adding the filtration, display it under the search bar:
![Снимок экрана 2023-11-28 в 20 17 33](https://github.com/kpi-ua/api.campus.kpi.ua/assets/58970455/6c685a11-4006-4de0-aae8-a6bbe6122b47)

**Comment by qqlexa** [comment]
Now, screens are not available.
