### ISSUE TITLE
The "Share profile" button is absent.

### ISSUE THREAD

**Issue by ernado-x** [kpi-ua/intellect.kpi.ua#87]
Actual:
<img width="1194" alt="Screenshot 2023-12-02 at 22 56 41" src="https://github.com/kpi-ua/intellect.kpi.ua/assets/3822922/11e45bbf-a587-42d4-8c65-8492b7e87cf9">

Expected:
<img width="1076" alt="Screenshot 2023-12-02 at 22 56 55" src="https://github.com/kpi-ua/intellect.kpi.ua/assets/3822922/a9521274-463f-4ce3-a3e3-ce6a839a96b7">

**Comment by Oleks-Y** [comment]
iti's fixed now, isn't it ?

**Comment by ernado-x** [comment]
@Oleks-Y I do not see this button on the desktop or mobile version.
